config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, except: [:edit, :update] do
    member do
      get :activate
      get :reset_password
      post :reset_password
    end
    collection do
      get :claim_password
      post :claim_password
      get :edit
      put :update
    end
  end

  resources :notifications

  resources :flights do
    get :autocomplete_airport_name, on: :collection
    post :refresh, on: :member
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create', as: :log_in
  post 'logout' => 'user_sessions#destroy', as: :logout

end

app/models/airline.rb
class Airline < ActiveRecord::Base
  has_many :airports
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :flights
  belongs_to :airline
  has_and_belongs_to_many :connected_airports, -> { uniq },
                          class_name: 'Airport',
                          join_table: 'airports_connections',
                          foreign_key: 'airport_id',
                          association_foreign_key: 'connected_airport_id'
  validates_presence_of :name
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :user
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :destination_airport, class_name: 'Airport'
  has_one :airline, through: :departure_airport

  has_many :prices, dependent: :destroy
  has_many :notifications

  scope :with_name, -> (name) { where('lower(name) ILIKE ?', name.downcase) }
  scope :with_full_name, -> (name) { where('lower(full_name) ILIKE ?', name.downcase) }

  validates_presence_of :user

  def current_price
    prices.last
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :flight

  scope :unread, -> { where(read: false) }
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :flight
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :email, uniqueness: true, presence: true
  validates_length_of :password, minimum: 3, message: "password must be at least 3 characters long", if: :password
  validates_confirmation_of :password, message: "should match confirmation", if: :password

  has_many :flights
  has_many :notifications, through: :flights
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protected

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  expose_decorated(:flights) { current_user.flights }
  expose_decorated(:flight)
  autocomplete(:airport, :name, full: true)

  def create
    flight_factory = FlightFactory.new(current_user, departure_airport, destination_airport, date)
    flight = flight_factory.create
    if flight.save
      redirect_to flight, notice: 'Flight successfully created'
    else
      redirect_to flights_path, alert: 'Error'
    end
  end

  def refresh
    updater = FlightUpdater.new(flight)
    updater.call!
    if flight.save
      redirect_to flight, notice: 'Flight successfully updated'
    else
      redirect_to flight, warning: 'Error'
    end
  end

  private

  def departure_airport
    flight_params[:departure_airport][:name]
  end

  def destination_airport
    flight_params[:arrival_airport][:name]
  end

  def date
    "#{flight_params['departure_date(1i)']}-#{flight_params['departure_date(2i)']}-#{flight_params['departure_date(3i)']}"
  end

  def flight_params
    params[:flight]
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  expose(:notifications) { current_user.notifications }
  expose(:notification)
  expose_decorated(:flight) { notification.flight }

  def show
    notification.update_attribute(:read, true)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login

  def new
  end

  def create
    if login(params[:user][:email], params[:user][:password])
      #TODO route to redirect
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user, attributes: :user_params)

  def create
    if user.save
      user.activate!
      redirect_to root_path, notice: 'Account successfully created.'
    else
      render 'new'
    end
  end

  def update
    if user.save
      redirect_to account_path, notice: 'Account successfully updated.'
    else
        flash.now[:error] = 'error'
      render 'edit'
    end
  end

  def activate
    if user = User.load_from_activation_token(params[:id])
      user.activate!
      redirect_to(login_path, notice: 'User was successfully activated.')
    else
      not_authenticated
    end
  end

  def claim_password
    if request.post?
      if user = User.where(email: params[:user][:email]).first
        user.deliver_reset_password_instructions!
        redirect_to(login_path, notice: 'Password instructions were sent to your email.')
      else
        flash.now[:error] = 'Email not found.'
        render :claim_password
      end
    end
  end

  def reset_password
    user = User.load_from_reset_password_token params[:id]
    if request.post?
      if pass_params[:user][:password].eql? pass_params[:user][:password_confirmation]
        user.change_password! pass_params[:user][:password]
        redirect_to(login_path, notice: 'Password successfully changed.')
      else
        flash.now[:error] = 'Passwords do not match'
        render 'reset_password'
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_flash
    content_tag(:div, :id => :flashes) do
      flash.map do |k,v|
        type = k == 'notice' ? "success" : "danger"
        concat(content_tag(:div, :class => "alert alert-#{type}") do
          concat(content_tag(:p, v))
        end)
      end
    end unless flash.empty?
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.haml
%p= link_to flight.description, flight_path(flight.id)
%p= flight.dates
%p= flight.current_price
%hr

app/views/flights/index.html.haml
= link_to "Create new flight", new_flight_path
- if flights.present?
  - flights.each do |flight|
    = render 'flight', flight: flight
- else
  No flights

app/views/flights/new.html.haml
= simple_form_for flight do |f|
  = f.simple_fields_for :departure_airport do | d_airport_f |
    %p Departure airport
    = d_airport_f.input :name, url: autocomplete_airport_name_flights_path, as: :autocomplete, id_element: '#flight_departure_airport_airport_id'
    = d_airport_f.hidden_field :airport_id
  = f.simple_fields_for :arrival_airport do | a_airport_f |
    %p Arrival airport
    = a_airport_f.input :name, url: autocomplete_airport_name_flights_path, as: :autocomplete, id_element: '#flight_arrival_airport_airport_id'
    = a_airport_f.hidden_field :airport_id
  = f.input :departure_date, as: :date, order: [:day, :month, :year]
  = f.submit 'Create flight', class: 'btn btn-primary'

app/views/flights/show.html.haml
%h2= "Flight from #{flight.departure_airport.full_name} #{flight.departure_airport.name} to #{flight.destination_airport.full_name} #{flight.destination_airport.name}."
%p= "Departures at #{flight.departure_date} and arrives at #{flight.arrival_date}"
%p= "Current price: #{number_to_currency(flight.prices.last.normal, unit: flight.prices.last.currency, format: "%n %u")}."
%p= "Last updated at: #{flight.updated_at}."
= simple_form_for flight, url: refresh_flight_path(flight), method: :post do |f|
  = f.submit "Refresh flight!", class: 'btn btn-primary'
%p Prices history
- flight.prices.order('updated_at DESC').each do |price|
  %p= "#{number_to_currency(price.normal, unit: price.currency, format: "%n %u")} at #{price.updated_at}."

app/views/layouts/_login_modal.html.haml
#login-modal.modal.fade{"aria-hidden" => "true", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4.modal-title
          Login
      .modal-body
        = simple_form_for :user, url: log_in_path do |f|
          .form-group
            = f.input :email, label: false, placeholder: 'Email address'
          .form-group
            = f.input :password, label: false, placeholder: 'Password'
          = f.submit 'Login', class: 'btn btn-primary'
      .modal-footer
        %small
          Not a member?
          %a.signup{href: "#"} Sign up now!
        %br/
        %small
          %a{href: "#"} Forgotten password?

app/views/layouts/_signup_modal.html.haml
#signup-modal.modal.fade{"aria-hidden" => "true", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4.modal-title
          Sign Up
      .modal-body
        %h5 Account Information
        .form-group
          = simple_form_for :user, url: users_path, method: :post do |f|
            = f.input :email, label: false, placeholder: 'Email address'
            = f.input :password, label: false, placeholder: 'Password'
            = f.input :password_confirmation, label: false, placeholder: 'Password confirmation'
            = f.submit "Sign up", class: 'btn btn-primary'
      .modal-footer
        %small
          Already signed up?
          = link_to "Login here", login_path

app/views/notifications/index.haml
.notifications
  - notifications.each do |notification|
    .notification
      = link_to 'Notification', notification_path(notification), class: notification.read ? :read : :unread

app/views/notifications/show.haml
%h2 Notification
%p= "Price has changed for #{flight.description}"
= link_to 'Click here to preview flight', flight_path(flight)

app/views/user_sessions/_login_form.html.haml
.row
  .col-xs-8.col-xs-offset-2
    %h4 Sign in!
    .push
    = simple_form_for :user do |f|
      = f.input :email
      = f.input :password
      = f.submit class: "btn btn-primary"

app/views/user_sessions/new.html.haml
%hr
= render partial: 'login_form'
%hr

app/views/users/claim_password.html.haml
%h2 Reset your password

= simple_form_for :user, url: claim_password_users_path, method: :post do |f|
  = f.input :email
  = f.submit 'Submit', class: 'btn btn-primary'

app/views/users/new.html.haml
%hr

.row
  .col-xs-8.col-xs-offset-2
    %h4 Create your account!
    = simple_form_for :user, url: users_path, method: :post do |f|
      = f.input  :email
      = f.input :password
      = f.input :password_confirmation
      = f.submit "Create account", class: 'btn btn-primary'

    %p
      %small
        Already have an account?
        = link_to "Sign in here.", login_path
    %p
      %small
        Forgot your password?
        = link_to "Reset here.", "PLACE PATH HERE"
    %p
      %small
        FlightsApp
        = link_to "Find out how it works...", "#"

%hr

app/views/users/reset_password.html.haml
%h2 Reset password

= simple_form_for user, url: reset_password_user_path, method: :post do |f|
  = f.input :password, label: 'New password'
  = f.input :password_confirmation
  = f.submit 'Save', class: 'btn btn-primary'

app/views/welcome/index.html.haml
%h1 Welcome to FlightsApp site!
- unless logged_in?
  %p Sign up or login to continue.
- else
  = link_to "Browse your flights.", flights_path